i1=int(input("enter first integer:"))
i2=int(input("enter second integer:"))
i3=int(input("enter third integer:"))
f1=float(input("enter first float:"))
f2=float(input("enter second float:"))
f3=float(input("enter third float:"))
s1=str(input("enter first string:"))
s2=str(input("enter second string:"))
c=complex(input("enter complex number:"))
print("first integer:",i1)
print("second integer:",i2)
print("third integer:",i3)
print("first float:",f1)
print("second float:",f2)
print("third float:",f3)
print("first string:",s1)
print("second string:",s2)
print("complex number:",c)

